version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: metrics_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./metrics-collector/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pulse-network

  metrics-collector:
    build: ./metrics-collector
    restart: always
    environment:
      PORT: 3000
      PG_HOST: postgres
      PG_USER: user
      PG_PASSWORD: password
      PG_DB: metrics_db
      PG_PORT: 5432
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - pulse-network

  dashboard-frontend:
    build: ./dashboard-frontend
    restart: always
    ports:
      - '8080:80'
    depends_on:
      - metrics-collector
    networks:
      - pulse-network

volumes:
  postgres-data:


networks:
  pulse-network:
    driver: bridge
